### ISSUE TITLE
Be strongly opinionated about credentials management?

### ISSUE THREAD

**Issue by cjcjameson** [marcingrzejszczak/concourse-pipeline#2]
Hi Marcin,

Neat stuff. One thing that we've had to develop a strong opinion about on my team is credential management.

It's nice that you provide a default credentials template, but perhaps we should have some strong wording or clear direction about where we recommend that people put these credentials? I didn't see anything in the deck, so I figured here's as good a place as any to drop the idea in.

Admittedly, we are waiting for Concourse to perhaps provide a different implementation of credentials, such as with Vault.

Thanks and rock on,
C.J.

**Comment by marcingrzejszczak** [comment]
Hi @cjcjameson ! I have completely missed this issue!! Can you check out the https://github.com/spring-cloud/spring-cloud-pipelines if the problem has been solved there?

**Comment by cjcjameson** [comment]
Hi Marcin, yep, it seems like that place does have sufficiently clear opinions about credentials for now.

Thanks! Closing
